[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fundingme_dapp = "DmcSC8vFAoLr756aDoqkV13S6kosdHHNuziRezhCcKUi"

[programs.localnet]
fundingme_dapp = "DmcSC8vFAoLr756aDoqkV13S6kosdHHNuziRezhCcKUi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
